name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Ensure tag matches version
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          runCmd: just ensure-tag-matches-version ${{ github.ref_name }}

  build:
    needs: pre-build
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate build environment
        run: just can-build

      - name: Build in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          runCmd: just cross-compile ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksy-${{ matrix.target }}-artifact
          path: |
            dist/*.tar.gz
            dist/checksums.txt

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Merge checksums
        run: cat artifacts/*-checksum.txt > artifacts/checksums.txt

      - name: Sign checksums
        run: just sign artifacts/checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.tar.gz
            artifacts/checksums.txt
            artifacts/checksums.txt.sig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}